# Generated by Django 3.2.7 on 2021-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memento',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='memento',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='memento',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
